//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string hoTen { get; set; }
        public string role { get; set; }
    }
}
